/*
 * ============================================================================
 *  Project : Road Anomaly Detection System (RADS)
 *  File    : app/build.gradle.kts (module-level)
 *
 *  Build script for the `:app` Android application module. It applies the
 *  Android/Kotlin/KSP plugins, configures how the app is compiled and packaged
 *  (SDK levels, ABI filters, build types, Java/Kotlin targets, build features),
 *  and declares every runtime/processor dependency the app needs. This is the
 *  single source of truth for the app's build configuration and library versions.
 *
 *  Author  : Rutuja Kulkarni
 * ============================================================================
 */

// Apply the plugins that were registered (with versions) in the root build
// script. Applying them here actually activates them for this module.
plugins {
    id("com.android.application")            // Marks this module as an Android app (produces an APK/AAB).
    id("org.jetbrains.kotlin.android")       // Enables Kotlin compilation for Android.
    id("com.google.devtools.ksp")            // Runs KSP annotation processing (used by Room below).
}

// The `android {}` block configures the Android Gradle Plugin for this module.
android {
    // Base package for generated classes (e.g. BuildConfig, R) — decoupled from applicationId.
    namespace = "com.rads.detector"
    // SDK version the app is COMPILED against (gives access to API level 35 symbols).
    compileSdk = 35

    // `defaultConfig` holds settings baked into the app's manifest/build at the base level.
    defaultConfig {
        applicationId = "com.rads.detector"  // Unique app identity on-device and on the Play Store.
        minSdk = 26          // Android 8.0 — covers ~95% of devices
        targetSdk = 35       // API level the app is tested/optimized for (drives runtime behavior compat).
        versionCode = 1      // Internal integer version, must increase for each store upload.
        versionName = "1.0.0" // Human-readable version shown to users.

        // Filter native libs to reduce APK size (your phones are arm64)
        // Only these CPU architectures' native (.so) libraries are packaged, which
        // shrinks the APK by dropping x86/x86_64 variants the target phones never use.
        ndk {
            abiFilters += listOf("arm64-v8a", "armeabi-v7a")
        }
    }

    // Don't compress the .tflite asset — TFLite mmaps it for zero-copy load
    // Keeping the model uncompressed in the APK lets TensorFlow Lite memory-map
    // it directly, avoiding a decompression copy and speeding up model load.
    androidResources {
        noCompress += listOf("tflite", "lite")
    }

    // `buildTypes` define distinct build variants (e.g. release vs. debug).
    buildTypes {
        // Release: optimized, shippable build.
        release {
            isMinifyEnabled = true        // Run R8/ProGuard to strip & obfuscate unused code.
            isShrinkResources = true      // Remove resources no longer referenced after code shrinking.
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"), // Android's optimized default rules.
                "proguard-rules.pro"                                     // Project-specific keep rules.
            )
        }
        // Debug: developer build for fast iteration.
        debug {
            isMinifyEnabled = false       // No shrinking — faster builds & readable stack traces.
            applicationIdSuffix = ".debug" // Lets a debug build coexist with a release build on one device.
        }
    }

    // Target Java 17 bytecode for compiled Java sources and library compatibility.
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    // Kotlin must emit bytecode for the same JVM target as Java above (17).
    kotlinOptions {
        jvmTarget = "17"
    }

    // Opt into specific build features generated by AGP.
    buildFeatures {
        viewBinding = true   // Generate type-safe binding classes for layouts (no findViewById).
        buildConfig = true   // Generate the BuildConfig class (e.g. for build-time constants/flags).
    }

    // Control how files are merged when packaging the final APK.
    packaging {
        resources {
            // Drop duplicate license metadata files that multiple libraries ship,
            // which would otherwise cause "duplicate file" packaging errors.
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

// All third-party and AndroidX libraries this module links against.
dependencies {
    // Kotlin + coroutines
    implementation("androidx.core:core-ktx:1.13.1")                              // Kotlin-friendly extensions over the Android framework.
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")     // Coroutines + Android main-thread dispatcher for async work.

    // AppCompat + Material
    implementation("androidx.appcompat:appcompat:1.7.0")                         // Backward-compatible Activity/widgets across OS versions.
    implementation("com.google.android.material:material:1.12.0")                // Material Design components (buttons, themes) used in the UI.
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")           // Flexible flat layout engine used by the main screen.

    // Lifecycle
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.4")             // Lifecycle-aware coroutine scopes (e.g. lifecycleScope).
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.4")           // ViewModel support for surviving config changes.
    implementation("androidx.activity:activity-ktx:1.9.1")                       // Activity Result APIs (used for permission requests) + KTX helpers.

    // CameraX — the production camera stack
    val cameraxVersion = "1.3.4"                                                 // Single pinned version for all CameraX artifacts.
    implementation("androidx.camera:camera-core:$cameraxVersion")                // Core CameraX APIs and use-case framework.
    implementation("androidx.camera:camera-camera2:$cameraxVersion")             // Camera2-backed implementation of CameraX.
    implementation("androidx.camera:camera-lifecycle:$cameraxVersion")           // Binds the camera to an Android lifecycle automatically.
    implementation("androidx.camera:camera-view:$cameraxVersion")                // PreviewView widget used in activity_main.xml.

    // TensorFlow Lite — inference engine + GPU delegate
    implementation("org.tensorflow:tensorflow-lite:2.16.1")                      // Core on-device inference runtime.
    implementation("org.tensorflow:tensorflow-lite-gpu:2.16.1")                  // GPU delegate implementation for faster inference.
    implementation("org.tensorflow:tensorflow-lite-gpu-api:2.16.1")              // Public API surface for configuring the GPU delegate.
    implementation("org.tensorflow:tensorflow-lite-gpu-delegate-plugin:0.4.4")   // Helper plugin for wiring the GPU delegate via TFLite Support.
    implementation("org.tensorflow:tensorflow-lite-support:0.4.4")               // Image/tensor pre- & post-processing utilities.

    // Room — local SQLite for detection reports
    val roomVersion = "2.6.1"                                                    // Single pinned version for all Room artifacts.
    implementation("androidx.room:room-runtime:$roomVersion")                    // Room ORM runtime over SQLite.
    implementation("androidx.room:room-ktx:$roomVersion")                        // Coroutine/Flow support for Room queries.
    ksp("androidx.room:room-compiler:$roomVersion")                              // KSP processor that generates Room's DAO/DB code at compile time.

    // WorkManager — for future backend sync (Phase 2)
    implementation("androidx.work:work-runtime-ktx:2.9.1")                       // Reliable deferrable background work (planned report upload).

    // Location (FusedLocationProvider)
    implementation("com.google.android.gms:play-services-location:21.3.0")       // GPS/fused location used to tag detections with coordinates.

    // Preferences (settings storage)
    implementation("androidx.datastore:datastore-preferences:1.1.1")             // Modern async key-value store for user settings.
}
